models/Calculation.php
<?php

namespace app\models;


use yii\db\ActiveRecord;
use yii\db\Exception;

/**
 * Class Calculation
 * @package app\models
 * @property int $id [int(11)]
 * @property int $user_id [int(11)]
 * @property string $title [varchar(255)]
 * @property string $calculation
 * @property int $created_at [timestamp]
 * @property int $updated_at [timestamp]
 * @property CalculationCodes[] $codes
 */
class Calculation extends ActiveRecord
{
    public function rules()
    {
        return [
            [['user_id', 'title', 'calculation',], 'required'],
            [['title', 'calculation'], 'safe']
        ];
    }

    public function getCodes(){
        return $this->hasMany(CalculationCodes::className(), ['calculation_id' => 'id']);
    }

    public function beforeValidate()
    {
        $this->user_id = \Yii::$app->user->id;
        return parent::beforeValidate();
    }

    public function afterSave($insert, $changedAttributes)
    {


        if($insert || isset($changedAttributes['calculation'])) {
            $re = '/{[+-]{0,1}\d+}/';
            preg_match_all($re, $this->calculation, $matches);
            $codes = [];
            if(is_array($matches)){
                foreach ($matches as $match){
                    foreach ($match as $code){
                        $code = preg_replace('/[{}+]/', '', $code);
                        $codes[] = intval($code);
                    }
                }
            }

            if($codes){
                CalculationCodes::deleteAll(['calculation_id' => $this->id]);
                try {
                    foreach ($codes as $code) {
                        $model = new CalculationCodes();
                        $model->calculation_id = $this->id;
                        $model->code = $code;
                        $state = $model->save();
                        $state1 = $state;
                    }

                }catch (\Exception $e){

                    throw $e;
                }
            }
        }
        return parent::afterSave($insert, $changedAttributes);
    }
}

controllers/CalculationController.php
<?php
/**
 * Created by PhpStorm.
 * User: ursus
 * Date: 04.08.17
 * Time: 6:35
 */

namespace app\controllers;


use app\models\Calculation;
use app\models\CalculationList;
use Yii;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\helpers\VarDumper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

class CalculationController extends Controller
{

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['delete'],
                ],
            ],
        ];
    }


    public function actionIndex(){
        $model_list = new CalculationList();
        $model_list->load(Yii::$app->request->get());
        $provider = new ActiveDataProvider([
            'query' => $model_list->query(),
            'pagination' => [
                'pageSize' => 10,
            ],
        ]);

        return $this->render('list', [
            'model' => $model_list,
            'provider' => $provider
        ]);
    }

    public function actionItem(){
        if(Yii::$app->request->get('id')){
            $model = Calculation::findOne(Yii::$app->request->get('id'));
        }else{
            $model = new Calculation();
        }

        if(Yii::$app->request->post($model->formName())){
            $model->load(Yii::$app->request->post());
            if($model->save()){
                Yii::$app->session->setFlash('success', 'Calculation saved');
                return $this->redirect(Yii::$app->urlManager->createUrl(['calculation/item','id' => $model->id]));
            }
        }
        return $this->render('item', [
            'model' => $model,
            'codes' => $model->codes
        ]);
    }



    public function actionDelete(){
        $model = Calculation::findOne(Yii::$app->request->get('id'));
        if(!$model){
            throw new NotFoundHttpException('calculation not found');
        }
        if($model->delete()){
            Yii::$app->session->setFlash('success', 'Calculation deleted');
            return $this->redirect(Yii::$app->urlManager->createUrl(['calculation']));
        }
    }
}

views/calculation/item.php
<?php
/**
 * @var \app\models\Calculation $model
 */
$form = \yii\bootstrap\ActiveForm::begin(['action' => Yii::$app->urlManager->createUrl(['/calculation/item','id' => $model->id])]);

?>

<?=$form->field($model, 'title')->textInput();?>
<?=$form->field($model, 'calculation')->textarea();?>
<?php if($codes){?>
    <div class="row">

        <div class="col-sm-12">
            <h5>Codes</h5>
        <?php  foreach ($codes as $code){
            echo "$code->code ";
        }?>
        </div>
    </div>
<?php }?>
<?=\yii\bootstrap\Html::button('Save', ['type'=>'submit', 'class' => 'btn btn-success'])?>

<?php
\yii\bootstrap\ActiveForm::end();
?>

views/calculation/list.php
<?php
/**

 * @var \yii\data\ActiveDataProvider $provider
 * @var \app\models\CalculationList $model
 */

use yii\bootstrap\Html;
use yii\widgets\Pjax;

Pjax::begin(['linkSelector' => '.pagination a', 'timeout' => 1500]);

?>
<div class="text-right">
    <?= Html::a('Add', '/calculation/item', ['class' => 'btn btn-success calculation-add'])?>
</div>
<?php
	$form = \yii\widgets\ActiveForm::begin(['method' => 'get']);
?>
	<div class="row">
		<div class="col-md-4">
			<?=$form->field($model, 'operation')->dropDownList(\app\models\CalculationList::$operations_labels)?>
		</div>
		<div class="col-md-4">
            <?=$form->field($model, 'value')->textInput()?>
		</div>
		<div class="col-md-4">
			<?=Html::button('Find', ['class' => 'btn btn-success calculation-list-btn-find', 'type' => 'submit'])?>
		</div>
	</div>
<?
\yii\widgets\ActiveForm::end();
echo \yii\grid\GridView::widget([
    'dataProvider' => $provider,
    'columns' => [
        'id',
        'title',
        [
            'class' => 'yii\grid\ActionColumn',
			'template' => '{view} {delete}',
			'buttons' => [
					'view' => function($url, $model, $key){
                        return Html::a('', Yii::$app->urlManager->createUrl(['/calculation/item', 'id' => $model['id']]), ['class' => 'glyphicon glyphicon-eye-open', "aria-hidden"=> "true"]);
					},
					'delete' => function($url, $model, $key){
                        return Html::a('', Yii::$app->urlManager->createUrl(['/calculation/delete', 'id' => $model['id']]), ['class' => 'glyphicon glyphicon-trash calculation-delete', "aria-hidden"=> "true"]);
					}
			]
        ]
    ]
 ]);


 Pjax::end();